// ─── MOCK DATA — erstattes med Supabase i næste fase ─────────────────────────

export const MOCK_CUSTOMER = {
  id: "cust_001",
  name: "Lasse Thomsen",
  company: "Nordic Bioscience A/S",
  email: "lasse@nordicbioscience.com",
  initials: "LT",
};

export const MOCK_SUPPLIER = {
  id: "supp_001",
  name: "Mette Paulsen",
  company: "TechConsult ApS",
  email: "mette@techconsult.dk",
  initials: "MP",
};

export type RequestStatus = "active" | "reviewing" | "completed" | "cancelled";
export type OfferStatus = "pending" | "accepted" | "rejected" | "withdrawn";
export type CandidateStatus = "new" | "approved" | "rejected" | "interviewing";

export const MOCK_REQUESTS = [
  {
    id: "req_001",
    title: "Senior Azure-arkitekt",
    competencies: ["Cloud-løsninger", "Microsoft-teknologi", "Arkitektur"],
    description: "Vi søger en erfaren Azure-arkitekt til at drive vores cloud-migrationsprojekt. Kandidaten skal have minimum 5 års erfaring med Azure og have arbejdet med enterprise-løsninger.",
    startDate: "2026-03-01",
    duration: "6 mdr.",
    workForm: "Hybrid",
    scope: "Fuldtid",
    status: "reviewing" as RequestStatus,
    createdAt: "2026-02-15",
    candidatesCount: 5,
    newCandidates: 2,
  },
  {
    id: "req_002",
    title: "Data & BI specialist",
    competencies: ["Data & BI", "Microsoft-teknologi"],
    description: "Vi har brug for en Power BI specialist til at bygge vores nye rapporteringsplatform.",
    startDate: "2026-04-01",
    duration: "3 mdr.",
    workForm: "Onsite",
    scope: "Deltid",
    status: "active" as RequestStatus,
    createdAt: "2026-02-18",
    candidatesCount: 0,
    newCandidates: 0,
  },
  {
    id: "req_003",
    title: "IT Projektleder",
    competencies: ["Projekt- & forandringsledelse"],
    description: "Erfaren IT projektleder søges til at styre implementering af nyt ERP-system.",
    startDate: "2026-02-01",
    duration: "12 mdr.",
    workForm: "Hybrid",
    scope: "Fuldtid",
    status: "completed" as RequestStatus,
    createdAt: "2026-01-10",
    candidatesCount: 7,
    newCandidates: 0,
  },
];

export const MOCK_CANDIDATES = [
  {
    id: "cand_001",
    requestId: "req_001",
    name: "Anders Nielsen",
    title: "Senior Cloud Architect",
    company: "CloudPro ApS",
    experience: "8 år",
    rate: "1.250 kr/t",
    availability: "1. marts 2026",
    location: "København",
    nearshore: false,
    skills: ["Azure", "Terraform", "Kubernetes", "DevOps", "CI/CD"],
    summary: "Erfaren Azure-arkitekt med dyb ekspertise i enterprise cloud-migrationer. Har gennemført 15+ større migrationsprojekter for danske virksomheder.",
    status: "new" as CandidateStatus,
    supplierId: "supp_001",
    supplierName: "TechConsult ApS",
  },
  {
    id: "cand_002",
    requestId: "req_001",
    name: "Sofia Kowalski",
    title: "Cloud Solutions Architect",
    company: "Nearshore IT Poland",
    experience: "6 år",
    rate: "850 kr/t",
    availability: "15. marts 2026",
    location: "Warszawa (remote)",
    nearshore: true,
    skills: ["Azure", "AWS", "GCP", "Terraform", "Python"],
    summary: "Stærk cloud-arkitekt med bred erfaring på tværs af alle tre store cloud-platforme. Flydende dansk og engelsk.",
    status: "approved" as CandidateStatus,
    supplierId: "supp_002",
    supplierName: "Nearshore Partners",
  },
  {
    id: "cand_003",
    requestId: "req_001",
    name: "Thomas Bergmann",
    title: "Azure Specialist",
    company: "IT Freelance",
    experience: "5 år",
    rate: "1.100 kr/t",
    availability: "1. april 2026",
    location: "Aarhus",
    nearshore: false,
    skills: ["Azure", "Power Platform", "M365", "Security"],
    summary: "Freelance Azure-specialist med fokus på sikkerhed og compliance. Microsoft Certified Solutions Expert.",
    status: "new" as CandidateStatus,
    supplierId: "supp_003",
    supplierName: "Freelance DK",
  },
  {
    id: "cand_004",
    requestId: "req_001",
    name: "Priya Sharma",
    title: "Senior Cloud Architect",
    company: "GlobalTech India",
    experience: "9 år",
    rate: "750 kr/t",
    availability: "1. marts 2026",
    location: "Bangalore (remote)",
    nearshore: true,
    skills: ["Azure", "Microservices", "Docker", "Java", "Spring Boot"],
    summary: "Senior arkitekt med fokus på microservices og containerisering. Har arbejdet med nordiske kunder i 4 år.",
    status: "rejected" as CandidateStatus,
    supplierId: "supp_004",
    supplierName: "GlobalTech",
  },
  {
    id: "cand_005",
    requestId: "req_001",
    name: "Kasper Lund",
    title: "Cloud & Infrastructure Architect",
    company: "Konsulent Bureau A/S",
    experience: "7 år",
    rate: "1.300 kr/t",
    availability: "1. marts 2026",
    location: "København",
    nearshore: false,
    skills: ["Azure", "Infrastructure", "Networking", "Security", "ITIL"],
    summary: "Bred erfaring med hele cloud-stacken fra infrastruktur til applikationsarkitektur. Certificeret i Azure og ITIL.",
    status: "interviewing" as CandidateStatus,
    supplierId: "supp_005",
    supplierName: "Konsulent Bureau A/S",
  },
];

export const MOCK_MESSAGES = [
  {
    id: "msg_001",
    requestId: "req_001",
    from: "FindITconsultants.com Teamet",
    fromInitials: "LOGO",
    text: "Hej Lasse! Vi har nu modtaget 5 kandidater til din Azure-arkitekt søgning. Vi anbefaler særligt Anders Nielsen og Kasper Lund som stærke match. Vil du have et opkald for at gennemgå dem?",
    time: "I dag 09:14",
    isOwn: false,
  },
  {
    id: "msg_002",
    requestId: "req_001",
    from: "Lasse Thomsen",
    fromInitials: "LT",
    text: "Tak! Det ser godt ud. Jeg har godkendt Sofia og Kasper. Kan I arrangere interviews med dem begge i næste uge?",
    time: "I dag 10:32",
    isOwn: true,
  },
  {
    id: "msg_003",
    requestId: "req_001",
    from: "FindITconsultants.com Teamet",
    fromInitials: "LOGO",
    text: "Selvfølgelig! Jeg sender kalenderinvitationer ud nu. Forventer at have begge interviews booket inden for 24 timer.",
    time: "I dag 10:45",
    isOwn: false,
  },
];

export const MOCK_DOCUMENTS = [
  { id: "doc_001", name: "Opgavebeskrivelse — Azure-arkitekt.pdf", size: "245 KB", date: "15. feb 2026", type: "pdf", requestId: "req_001" },
  { id: "doc_002", name: "NDA — Nordic Bioscience.pdf", size: "128 KB", date: "15. feb 2026", type: "pdf", requestId: "req_001" },
  { id: "doc_003", name: "Kandidat sammenligning — req_001.xlsx", size: "89 KB", date: "20. feb 2026", type: "xlsx", requestId: "req_001" },
  { id: "doc_004", name: "Kontrakt — Kasper Lund.pdf", size: "312 KB", date: "22. feb 2026", type: "pdf", requestId: "req_001" },
];

export const MOCK_SUPPLIER_REQUESTS = [
  {
    id: "sreq_001",
    title: "Senior Azure-arkitekt",
    company: "Anonym virksomhed",
    competencies: ["Cloud-løsninger", "Microsoft-teknologi", "Arkitektur"],
    startDate: "2026-03-01",
    duration: "6 mdr.",
    workForm: "Hybrid",
    scope: "Fuldtid",
    location: "København",
    deadline: "2026-02-28",
    status: "open",
    postedAt: "2026-02-15",
  },
  {
    id: "sreq_002",
    title: "Cybersecurity Specialist",
    company: "Anonym virksomhed",
    competencies: ["Cybersecurity & Compliance"],
    startDate: "2026-04-01",
    duration: "12 mdr.",
    workForm: "Onsite",
    scope: "Fuldtid",
    location: "Aarhus",
    deadline: "2026-03-15",
    status: "open",
    postedAt: "2026-02-18",
  },
  {
    id: "sreq_003",
    title: "Power BI Developer",
    company: "Anonym virksomhed",
    competencies: ["Data & BI", "Microsoft-teknologi"],
    startDate: "2026-03-15",
    duration: "3 mdr.",
    workForm: "Remote",
    scope: "Deltid",
    location: "Remote",
    deadline: "2026-02-25",
    status: "closed",
    postedAt: "2026-02-10",
  },
];

export const MOCK_OFFERS = [
  {
    id: "off_001",
    requestId: "sreq_001",
    title: "Senior Azure-arkitekt",
    candidateName: "Mette Paulsen",
    rate: "1.150 kr/t",
    submittedAt: "2026-02-16",
    status: "pending" as OfferStatus,
  },
  {
    id: "off_002",
    requestId: "sreq_003",
    title: "Power BI Developer",
    candidateName: "Jonas Eriksen",
    rate: "950 kr/t",
    submittedAt: "2026-02-12",
    status: "accepted" as OfferStatus,
  },
  {
    id: "off_003",
    requestId: "sreq_002",
    title: "Cybersecurity Specialist",
    candidateName: "Anna Christensen",
    rate: "1.200 kr/t",
    submittedAt: "2026-02-19",
    status: "pending" as OfferStatus,
  },
];

export const MOCK_INVOICES = [
  { id: "inv_001", number: "2026-001", client: "Nordic Bioscience A/S", amount: "38.000 kr", period: "Jan 2026", status: "paid", dueDate: "2026-02-01" },
  { id: "inv_002", number: "2026-002", client: "Nordic Bioscience A/S", amount: "38.000 kr", period: "Feb 2026", status: "pending", dueDate: "2026-03-01" },
  { id: "inv_003", number: "2025-012", client: "DSV A/S", amount: "52.500 kr", period: "Dec 2025", status: "paid", dueDate: "2026-01-01" },
];
